[package]
name = "omvcs-storage-mock"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
omvcs-storage = { path = "../omvcs-storage" }
omvcs-model = { path = "../omvcs-model" }
sha2 = "0.10"

[dev-dependencies]
omvcs-core = { path = "../omvcs-core" }
serde_json = "1"
